In [1]:
# Numpy offers random module:
from numpy import random

In [5]:
# generate rand int between 0 and 30
x = random.randint(30)
x

14

In [6]:
# generate random float between 0 and 1
x = random.rand()
x

0.6298972627827348

In [7]:
# Generate random 1-D array with sizeof 10 and between 0,40

arr = random.randint(40, size=10)
arr

array([21, 23, 23, 35,  8,  0, 37, 17, 29, 23])

In [9]:
# Generate random 1-D array with size of 10

arr = random.rand(10)
arr

array([0.50492191, 0.50214089, 0.28431854, 0.39961168, 0.9285627 ,
       0.6298529 , 0.94199488, 0.50287385, 0.35948282, 0.31100763])

In [10]:
# Generate random 2-D array with size of 2 rows and 4 cols

arr = random.rand(2,4)
arr

array([[0.34190317, 0.14266159, 0.25512877, 0.51080791],
       [0.02985774, 0.43874265, 0.09019935, 0.76513027]])

In [11]:
# Generate random number from an array with choice()
a = random.choice([8,9,3,2,55,34])
a

9

In [13]:
# Generate a 2-D array that consists of the values in the array parameter
arr2d = random.choice([4,3,2,77,5,55], size=(2,4))
arr2d


array([[ 3,  2, 77, 55],
       [ 5, 55,  3,  3]])