In [1]:
import numpy as np

In [9]:
# generate 20 random elements between 0 and 1
arr1 =  np.random.random(20)
arr1

array([0.68156536, 0.59805395, 0.83352639, 0.79015493, 0.46527758,
       0.1800214 , 0.24177951, 0.48379422, 0.14326051, 0.68523307,
       0.03912984, 0.31688502, 0.19712467, 0.47145328, 0.78382505,
       0.00678383, 0.11776061, 0.62121716, 0.36155591, 0.35552253])

In [15]:
arr2 = np.array([1,2,3,4,5])
arr3 = np.array([6,7,8,9,10])

In [16]:
# exp of elements -> e ^ x
np.exp(arr2)


array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [19]:
# sum of elements
np.add(arr2,arr3)

array([ 7,  9, 11, 13, 15])

In [18]:
# multipy elements
np.multiply(arr2,arr3)

array([ 6, 14, 24, 36, 50])

In [20]:
# get min
np.minimum(arr2, arr3)

array([1, 2, 3, 4, 5])

In [22]:
#get max
np.maximum(arr2, arr3)

array([ 6,  7,  8,  9, 10])