In [1]:
import numpy as np

In [2]:
np1 = np.array([0,1,2,3,4,5])

# Create a view
# view is a copy but connected to the original one
np2 = np1.view()

print(f"Original np1: {np1}")
print(f"Original np2: {np2}")

Original np1: [0 1 2 3 4 5]
Original np2: [0 1 2 3 4 5]


In [3]:
# If we change the org, the view will change
np1[0] = 89
print(f"Original np1: {np1}")
print(f"Original np2: {np2}")

Original np1: [89  1  2  3  4  5]
Original np2: [89  1  2  3  4  5]


In [4]:
# If we change the view, the org will change
np2[2] = 0
print(f"Original np1: {np1}")
print(f"Original np2: {np2}")

Original np1: [89  1  0  3  4  5]
Original np2: [89  1  0  3  4  5]


In [5]:
# Create a copy
np1 = np.array([0,1,2,3,4,5])

np2 = np1.copy()

print(f"Original np1: {np1}")
print(f"Changed np2: {np2}")

Original np1: [0 1 2 3 4 5]
Changed np2: [0 1 2 3 4 5]


In [6]:
# If we change the org, the copy won't change
np1[0] = 40
print(f"Original np1: {np1}")
print(f"Changed np2: {np2}")

Original np1: [40  1  2  3  4  5]
Changed np2: [0 1 2 3 4 5]


In [7]:
# If we change the copy, the original won't change
np2[2] = 0
print(f"Original np1: {np1}")
print(f"Changed np2: {np2}")

Original np1: [40  1  2  3  4  5]
Changed np2: [0 1 0 3 4 5]


Practice

In [11]:
org = np.array([1,2,3,4,5])

view  = org.view()
view

array([1, 2, 3, 4, 5])

In [12]:
view[2] = 0

print(org)
print(view)

[1 2 0 4 5]
[1 2 0 4 5]


In [13]:
org[4] = -3

print(org)
print(view)

[ 1  2  0  4 -3]
[ 1  2  0  4 -3]


In [14]:
copy = org.copy()
copy

array([ 1,  2,  0,  4, -3])

In [17]:
copy[0] = 70

print(org)
print(copy)

[ 1  2  0  4 -3]
[70  2  0  4 -3]


In [18]:
org[3] = 29

print(org)
print(copy)

[ 1  2  0 29 -3]
[70  2  0  4 -3]


In [19]:
arr = np.arange(100)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
arr = arr.reshape(20,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [22]:
arr[3,0]

15

In [23]:
arr[3][0]

15

In [28]:
arr = arr.reshape(25, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])