In [1]:
import numpy as np

In [6]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
x = [True,False,False, False,True, False, False, False, False, True]

print(np1)
print(np1[x])

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  5 10]


In [9]:
filtered = []
for a in np1:
  if a % 2 == 0:
    filtered.append(True)
  else:
    filtered.append(False)

print(filtered)
# show cells witch are True
print(np1[filtered])

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [13]:
# Shortcut!!
filtered = np1 % 3 == 0
print(filtered)
# np1 with that filter
print(np1[filtered])

[False False  True False False  True False False  True False]
[3 6 9]
