In [1]:
# *** numpy is a type of list but more powerful to work with huge data ***
# install with:
# pip install numpy
import numpy as np

In [2]:
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [3]:
list2 = ['fateme', 22, 'seifi', False, '995365105']
print(list2)

['fateme', 22, 'seifi', False, '995365105']


In [4]:
# Numpy - Numeric Python
# ndarray = n-dimensional array

np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
np1.shape

(10,)

In [9]:
# Range
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# Step
np3 = np.arange(0,10,3)
print(np3)

[0 3 6 9]


In [13]:
# Zero 
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
# Multidimensional zeros : 3 rows and 5 cols
np5 = np.zeros((3,5))
print(np5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
# Full : ten 6
np6 = np.full((10), 6)
print(np6)

[6 6 6 6 6 6 6 6 6 6]


In [16]:
# Multidimensional Full
np7 = np.full((3,5), 2)
print(np7)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [17]:
# Convert python list to numpy
myList = [1,2,3,4,5]
np8 = np.array(myList)
print(np8)

[1 2 3 4 5]
