In [1]:
import numpy as np

In [15]:
# Search
np1 = np.array([1,2,3,4,5,6,7,8,9, 3])
x = np.where(np1 == 3)
print(x)
print(x[0])
print(np1[x])

(array([2, 9], dtype=int64),)
[2 9]
[3 3]


In [12]:
x = np.where(np1 > 4)
x

(array([4, 5, 6, 7, 8], dtype=int64),)

In [20]:
# Return even numbers
flt = (np1 % 2 == 0)
print(np1[flt])

# --------------------
y = np.where(np1%2==0)
print(y)
print(np1[y])

[2 4 6 8]
(array([1, 3, 5, 7], dtype=int64),)
[2 4 6 8]
