In [2]:
import numpy as np

In [3]:
# Create a 1-D numpy array and get shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1.shape)

(12,)


In [4]:
# Create a 2-D numpy array and get shape (rows/cols)
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np2.shape)

(2, 5)


In [5]:
# Reshape 2-D
np3 = np1.reshape(3,4)
print(np3)
print(np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [6]:
# Reshape 3-D
np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [7]:
# Flatten to 1-D
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [9]:
# num of dimensions
np4.ndim

3

In [11]:
# num of elements
np4.size

12

In [15]:
list = [[7,7,7,7], [8,8,8,8]]
myNPArr = np.array(list)
myNPArr

array([[7, 7, 7, 7],
       [8, 8, 8, 8]])

In [17]:
newNp = np.full((24), 1)
newNp.reshape(3,8)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [19]:
newNP2 = np.ones(3)
newNP2

array([1., 1., 1.])

In [20]:
newNP3 = np.eye(6)
newNP3

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [24]:
e = np.empty(5)
e


array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 7.68638514e-312,
       0.00000000e+000])

In [25]:
e

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 7.68638514e-312,
       0.00000000e+000])