In [1]:
import numpy as np

In [2]:
arr = np.random.randn(5,3)
arr

array([[ 0.67489778,  1.09111994, -2.31668783],
       [-1.49218269, -0.83679503,  1.0294979 ],
       [ 0.14582557,  0.58914476, -0.28095911],
       [ 0.43480995,  2.16148802, -0.63914869],
       [ 0.06240305,  0.06862919,  0.66749971]])

In [3]:
# sum of elements
arr.sum()

1.3595425287270593

In [5]:
# avg of arr
arr.mean()

0.09063616858180396

In [6]:
# std
arr.std()

1.0660708355425261

In [7]:
# variance
arr.var()

1.1365070263943398

In [15]:
# apply condition
arr2 = np.array([[34,5,2,77,56,11,17],[30,4,56,89,21,4,60]])
np.where(arr2<20,-1, arr2)

array([[34, -1, -1, 77, 56, -1, -1],
       [30, -1, 56, 89, 21, -1, 60]])

In [18]:
# sort array
arr2.sort()
arr2

array([[ 2,  5, 11, 17, 34, 56, 77],
       [ 4,  4, 21, 30, 56, 60, 89]])