import numpy as np

In [4]:
import numpy as np

In [5]:
# Slicing Numpy Array
np1 = np.array([1,2,3,4,5,6,7,8,9])

# return 2,3,4,5
print(np1[1:5])

[2 3 4 5]


In [6]:
# Return from sth till the end of array
print(np1[4:])

[5 6 7 8 9]


In [7]:
# Return negative slices
print(np1[-4:-1])

[6 7 8]


In [8]:
# Steps
print(np1[1:5]) # 2-5
print(np1[1:5:2]) # 2-5 in steps of 2

[2 3 4 5]
[2 4]


In [9]:
# Steps on the entire array
print(np1[::2]) # steps of 2
print(np1[::3]) # steps of 3

[1 3 5 7 9]
[1 4 7]


In [10]:
# Slice a 2-d array
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

# Pull out a single item
print(np2[1][2])

8


In [11]:
# Slice a 2-d array
print(np2[0:1, 2:])

[[3 4 5]]


In [12]:
# Slice from both rows: 2,3 and 7 and 8
print(np2[:2,1:3])

[[2 3]
 [7 8]]


In [13]:
np1[2:5] = -2
print(np1)

[ 1  2 -2 -2 -2  6  7  8  9]


In [15]:
np1[:] = 0
print(np1)

[0 0 0 0 0 0 0 0 0]


In [14]:
np1 = np.array([1,2,3,4,5,6,7,8,9])
