In [1]:
import numpy as np

In [5]:
# sort function creates an array that is sorted form of org one
np1 = np.array([3,6,1,3,6,8,9])
np2 = np.sort(np1)
np2

array([1, 3, 3, 6, 6, 8, 9])

In [9]:
np3 = np.array(['J', 'T','E','O'])
np4 = np.sort(np3)
np4

array(['E', 'J', 'O', 'T'], dtype='<U1')

In [10]:
# Boolean
np5 = np.array([True, True, False, True, False])
np6 = np.sort(np5)
np6

array([False, False,  True,  True,  True])

In [12]:
# 2-d array
np7 = np.array([[5,4,7,2],[9,0,4,1]])
np8 = np.sort(np7)
np8

array([[2, 4, 5, 7],
       [0, 1, 4, 9]])