In [1]:
import numpy as np

In [7]:
np1 = np.array([0,1,2,-3,4,5,6,-7,8,-9])
print(np1)

[ 0  1  2 -3  4  5  6 -7  8 -9]


In [3]:
# Square route of each element
print(np.sqrt(np1))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [4]:
# Absolute value
print(np.absolute(np1))

[0 1 2 3 4 5 6 7 8 9]


In [9]:
# Exponents
print(np.exp(np1))

[1.00000000e+00 2.71828183e+00 7.38905610e+00 4.97870684e-02
 5.45981500e+01 1.48413159e+02 4.03428793e+02 9.11881966e-04
 2.98095799e+03 1.23409804e-04]


In [8]:
# Min/Max
print(np.min(np1))
print(np.max(np1))

-9
8


In [10]:
# Sign pos or neg
print(np.sign(np1))

[ 0  1  1 -1  1  1  1 -1  1 -1]


In [12]:
# Trig sin cos log
print(np.sin(np1))
print(np.cos(np1))
print(np.log(np1))

[ 0.          0.84147098  0.90929743 -0.14112001 -0.7568025  -0.95892427
 -0.2794155  -0.6569866   0.98935825 -0.41211849]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
[      -inf 0.         0.69314718        nan 1.38629436 1.60943791
 1.79175947        nan 2.07944154        nan]


C:\Users\wq\AppData\Local\Temp\ipykernel_5156\1744913412.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
C:\Users\wq\AppData\Local\Temp\ipykernel_5156\1744913412.py:4: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))
